# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Behavioural Economics Laboratory
tagline:          BEL@UWA
description:      'University of Western Australia'
url:              http://bel-uwa.github
baseurl:          /

author:
  name:           'Mark Ott'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
